### ISSUE TITLE
CSV import language.codename issue

### ISSUE THREAD

**Issue by hzik** [MilanLund/migration-tool#10]
When switching to CSV type the blue print format followed by same values that work for the JSON format throws "The object key "codename" in the "language.codename" object must not be an empty string in your import data item of index 0." error on https://migration-tool-kentico-cloud.herokuapp.com/

**Comment by MilanLund** [comment]
@hzik 
Hey, sorry for the very late answer. I have very limited resources for maintaining this project. 
It quite hard to guess where the issue really lies. Would be great if you could share as much information as possible so I can reproduce the issue on my end. (ie. what elements are used in the content type you are importing in, what are the codenames of language variants, and how the CSV looks like).
However, from the message you mention, it looks like the CSV is not correct.
FYI. the testing site has a new URL https://migration-tool-kentico-kontent.herokuapp.com/
