### ISSUE TITLE
CSV import always return success but import nothing

### ISSUE THREAD

**Issue by dc-fish-yu** [MilanLund/migration-tool#14]
I generated blueprint with the tool and fill in the data after second row, no matter what I input, it will show following logs in console:

Import data structure ok...
Import data and content models comparision ok...
Starting import...
Import successful. See information about imported items in the code editor above.

And the import data area will show:
{
   "message": []
}

But actually it created nothing.

**Comment by sysret** [comment]
Is there a fix planned for this?

**Comment by MilanLund** [comment]
@sysret @dc-fish-yu 
Hey guys, sorry for the very late answer. I have very limited resources for maintaining this project.
There was a breaking change in the new version of the csvtojson npm package I did not reflect in the app code. Sorry about that. I pushed a fix and is available at https://migration-tool-kentico-kontent.herokuapp.com/. May I ask you to check whether the fix did the job for you?
