### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by lakshanc** [MilanLund/migration-tool#16]
Getting following error when importing json data.
Unhandled rejection RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined

but the same json can import to other projects. 
Compared content type code names and all are same. 

![image](https://user-images.githubusercontent.com/63629350/79186429-2d81be00-7e37-11ea-83e5-fb55a2801541.png)

**Comment by MilanLund** [comment]
@lakshanc 
Hey, sorry for the very late answer. I have very limited resources for maintaining this project. 
It quite hard to guess where the issue really lies. Would be great if you could share as much information as possible so I can reproduce the issue on my end.
