### ISSUE TITLE
Add support for CSV

### ISSUE THREAD

**Issue by JanLenoch** [MilanLund/migration-tool#3]
As a KC user,
I need to import content items in the CSV format,
because
* I migrate data from applications that support only relational (tabular) formats (like Excel), or
* My content consists of a large amount of items of smaller size, or
* My content production process does not require the validation and formatting features of the Content inventory service UI, etc.

**Comment by MilanLund** [comment]
Support for CSV has been added. You can import data as well as generate blueprints. Please see the [readme](https://github.com/MilanLund/migration-tool/blob/master/README.md) file for more information.
