### ISSUE TITLE
The GUI does not display validation errors

### ISSUE THREAD

**Issue by JanLenoch** [MilanLund/migration-tool#4]
When importing the JSON with a formatting error (e.g. unnecessary comma at the end of an array listing, additional starting curly brace), the Logs window in the GUI does not display the validation error that the API endpoint returns.

Actual: "=== New data import at Mon, 04 Dec 2017 13:59:10 GMT==="
Expected: "The provided request body is invalid ..."

**Comment by MilanLund** [comment]
Fixed in [1677d438823d9f4f1d8648df8bde714dbb65bcf0](https://github.com/MilanLund/migration-tool/commit/1677d438823d9f4f1d8648df8bde714dbb65bcf0). I also added feature that highlights position of the erroe in the code editor.
