### ISSUE TITLE
(Low priority) JSON blueprints use different indentation rules than the "Import data" input window

### ISSUE THREAD

**Issue by JanLenoch** [MilanLund/migration-tool#5]
When a blueprint of a JSON input is generated and edited by the user, the indentation of the live edits follows different rules than those applied to the generation of the blueprint.

Expected:

	{
		"items": [{
			"item": {
				// ...
			},
			"variants": [{
				// ...
				},
				"elements": {
					"short_description": "<p>Lorem ipsum</p>",
					"full_service_level_agreement": "<p>Dolor sit amet</p>",
					"contact_person": "Jan Lenoch",
					"asset": [
						{
							"id": "84cea13e-d660-48d4-bc2e-2283495b4d5e"
						},
						{
							"id": "89f2491d-619c-4a96-8dd8-02bf6f638b89"
						}
					]
				}
			}]
		}]
	}

Actual

	{
		"items": [{
			"item": {
				// ...
			},
			"variants": [{
				// ...
				},
				"elements": {
					"short_description": "<p>Lorem ipsum</p>",
					"full_service_level_agreement": "<p>Dolor sit amet</p>",
					"contact_person": "Jan Lenoch",
					"asset": [{
						"id": "84cea13e-d660-48d4-bc2e-2283495b4d5e"
					},
							  {
								"id": "89f2491d-619c-4a96-8dd8-02bf6f638b89"
							  }]
				}
			}]
		}]
	}

**Comment by MilanLund** [comment]
Fixed in [8542240552bada7cceb0a08d471bb72c110b0b83](https://github.com/MilanLund/migration-tool/commit/8542240552bada7cceb0a08d471bb72c110b0b83).
Tab sizes and indentation has been unified in Codemirror and JS Beautifier.
