### ISSUE TITLE
Explain briefly the CSV header row in blueprints

### ISSUE THREAD

**Issue by JanLenoch** [MilanLund/migration-tool#6]
Leave a note in the readme that the "sitemap_locations/codename", "language_codename/asset/id" and similar identifiers are being built directly from the JSON hierarchy. That will help people understand why it's not "sitemap_locations_codename" and "language_codename/asset_id".

**Comment by MilanLund** [comment]
Fixed in [706f9d0d7567182ad812c7bd70582e268d941534](https://github.com/MilanLund/migration-tool/commit/706f9d0d7567182ad812c7bd70582e268d941534).
